name: Maestro E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  android:
    name: Android - Smoke Tests
    runs-on: macos-13
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Download APK
        run: |
          curl -L -o app.apk \
            "https://github.com/saucelabs/my-demo-app-rn/releases/download/v1.3.0/Android-MyDemoAppRN.1.3.0.build-244.apk"

      - name: Run Android smoke tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: Pixel_6
          script: adb install -r app.apk && sleep 15 && maestro test .maestro --include-tags=smoke --format junit --output report-android.xml -e MAESTRO_USERNAME=${{ secrets.MAESTRO_USERNAME }} -e MAESTRO_PASSWORD=${{ secrets.MAESTRO_PASSWORD }} -e MAESTRO_LOCKED_USERNAME=${{ secrets.MAESTRO_LOCKED_USERNAME }} -e MAESTRO_LOCKED_PASSWORD=${{ secrets.MAESTRO_LOCKED_PASSWORD }} -e MAESTRO_EMAIL_DOMAIN=${{ secrets.MAESTRO_EMAIL_DOMAIN }} -e MAESTRO_CARD_NUMBER=${{ secrets.MAESTRO_CARD_NUMBER }} -e MAESTRO_CARD_EXPIRATION=${{ secrets.MAESTRO_CARD_EXPIRATION }} -e MAESTRO_CARD_CVV=${{ secrets.MAESTRO_CARD_CVV }}

      - name: Upload Android test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-android
          path: report-android.xml